# Generated by Django 2.2.12 on 2020-06-02 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gxfghtgf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fthrt', models.BigIntegerField()),
                ('asrgfwfsc', models.BigIntegerField(blank=True, null=True)),
                ('sdferg', models.BigIntegerField(blank=True, null=True)),
                ('erfr', models.BigIntegerField(blank=True, null=True)),
                ('werfe', models.BigIntegerField(blank=True, null=True)),
                ('gujuykju', models.BigIntegerField(blank=True, null=True)),
                ('qsqsw', models.BigIntegerField(blank=True, null=True)),
                ('ewfergftr', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
    ]
